/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.cs3.publicsharev0alpha.FileType', null, global);
goog.exportSymbol('proto.cs3.publicsharev0alpha.Permission', null, global);
goog.exportSymbol('proto.cs3.publicsharev0alpha.PublicShare', null, global);
goog.exportSymbol('proto.cs3.publicsharev0alpha.UpdatePolicy', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.publicsharev0alpha.UpdatePolicy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.publicsharev0alpha.UpdatePolicy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.cs3.publicsharev0alpha.UpdatePolicy.displayName = 'proto.cs3.publicsharev0alpha.UpdatePolicy';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.publicsharev0alpha.UpdatePolicy.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.publicsharev0alpha.UpdatePolicy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.publicsharev0alpha.UpdatePolicy} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.publicsharev0alpha.UpdatePolicy.toObject = function(includeInstance, msg) {
  var f, obj = {
    setPassword: jspb.Message.getFieldWithDefault(msg, 1, false),
    setExpiration: jspb.Message.getFieldWithDefault(msg, 2, false),
    setPermission: jspb.Message.getFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.publicsharev0alpha.UpdatePolicy}
 */
proto.cs3.publicsharev0alpha.UpdatePolicy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.publicsharev0alpha.UpdatePolicy;
  return proto.cs3.publicsharev0alpha.UpdatePolicy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.publicsharev0alpha.UpdatePolicy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.publicsharev0alpha.UpdatePolicy}
 */
proto.cs3.publicsharev0alpha.UpdatePolicy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSetPassword(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSetExpiration(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSetPermission(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.publicsharev0alpha.UpdatePolicy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.publicsharev0alpha.UpdatePolicy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.publicsharev0alpha.UpdatePolicy} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.publicsharev0alpha.UpdatePolicy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSetPassword();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getSetExpiration();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getSetPermission();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional bool set_password = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.cs3.publicsharev0alpha.UpdatePolicy.prototype.getSetPassword = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.cs3.publicsharev0alpha.UpdatePolicy.prototype.setSetPassword = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool set_expiration = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.cs3.publicsharev0alpha.UpdatePolicy.prototype.getSetExpiration = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.cs3.publicsharev0alpha.UpdatePolicy.prototype.setSetExpiration = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool set_permission = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.cs3.publicsharev0alpha.UpdatePolicy.prototype.getSetPermission = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.cs3.publicsharev0alpha.UpdatePolicy.prototype.setSetPermission = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.publicsharev0alpha.PublicShare = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.publicsharev0alpha.PublicShare, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.cs3.publicsharev0alpha.PublicShare.displayName = 'proto.cs3.publicsharev0alpha.PublicShare';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.publicsharev0alpha.PublicShare.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.publicsharev0alpha.PublicShare.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.publicsharev0alpha.PublicShare} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.publicsharev0alpha.PublicShare.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    token: jspb.Message.getFieldWithDefault(msg, 2, ""),
    filename: jspb.Message.getFieldWithDefault(msg, 3, ""),
    fileType: jspb.Message.getFieldWithDefault(msg, 4, 0),
    expiration: jspb.Message.getFieldWithDefault(msg, 5, 0),
    passwordProtected: jspb.Message.getFieldWithDefault(msg, 6, false),
    permission: jspb.Message.getFieldWithDefault(msg, 7, 0),
    displayName: jspb.Message.getFieldWithDefault(msg, 8, ""),
    owner: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.publicsharev0alpha.PublicShare}
 */
proto.cs3.publicsharev0alpha.PublicShare.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.publicsharev0alpha.PublicShare;
  return proto.cs3.publicsharev0alpha.PublicShare.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.publicsharev0alpha.PublicShare} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.publicsharev0alpha.PublicShare}
 */
proto.cs3.publicsharev0alpha.PublicShare.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    case 4:
      var value = /** @type {!proto.cs3.publicsharev0alpha.FileType} */ (reader.readEnum());
      msg.setFileType(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setExpiration(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPasswordProtected(value);
      break;
    case 7:
      var value = /** @type {!proto.cs3.publicsharev0alpha.Permission} */ (reader.readEnum());
      msg.setPermission(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setDisplayName(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwner(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.publicsharev0alpha.PublicShare.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.publicsharev0alpha.PublicShare.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.publicsharev0alpha.PublicShare} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.publicsharev0alpha.PublicShare.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFileType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getExpiration();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getPasswordProtected();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getPermission();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getDisplayName();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getOwner();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.cs3.publicsharev0alpha.PublicShare.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.cs3.publicsharev0alpha.PublicShare.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string token = 2;
 * @return {string}
 */
proto.cs3.publicsharev0alpha.PublicShare.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.cs3.publicsharev0alpha.PublicShare.prototype.setToken = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string filename = 3;
 * @return {string}
 */
proto.cs3.publicsharev0alpha.PublicShare.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.cs3.publicsharev0alpha.PublicShare.prototype.setFilename = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional FileType file_type = 4;
 * @return {!proto.cs3.publicsharev0alpha.FileType}
 */
proto.cs3.publicsharev0alpha.PublicShare.prototype.getFileType = function() {
  return /** @type {!proto.cs3.publicsharev0alpha.FileType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.cs3.publicsharev0alpha.FileType} value */
proto.cs3.publicsharev0alpha.PublicShare.prototype.setFileType = function(value) {
  jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional uint64 expiration = 5;
 * @return {number}
 */
proto.cs3.publicsharev0alpha.PublicShare.prototype.getExpiration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.cs3.publicsharev0alpha.PublicShare.prototype.setExpiration = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool password_protected = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.cs3.publicsharev0alpha.PublicShare.prototype.getPasswordProtected = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.cs3.publicsharev0alpha.PublicShare.prototype.setPasswordProtected = function(value) {
  jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional Permission permission = 7;
 * @return {!proto.cs3.publicsharev0alpha.Permission}
 */
proto.cs3.publicsharev0alpha.PublicShare.prototype.getPermission = function() {
  return /** @type {!proto.cs3.publicsharev0alpha.Permission} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {!proto.cs3.publicsharev0alpha.Permission} value */
proto.cs3.publicsharev0alpha.PublicShare.prototype.setPermission = function(value) {
  jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional string display_name = 8;
 * @return {string}
 */
proto.cs3.publicsharev0alpha.PublicShare.prototype.getDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.cs3.publicsharev0alpha.PublicShare.prototype.setDisplayName = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string owner = 9;
 * @return {string}
 */
proto.cs3.publicsharev0alpha.PublicShare.prototype.getOwner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.cs3.publicsharev0alpha.PublicShare.prototype.setOwner = function(value) {
  jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * @enum {number}
 */
proto.cs3.publicsharev0alpha.Permission = {
  PERMISSION_INVALID: 0,
  PERMISSION_VIEW_ONLY: 1,
  PERMISSION_MODIFY: 2,
  PERMISSION_DROP_ONLY: 3
};

/**
 * @enum {number}
 */
proto.cs3.publicsharev0alpha.FileType = {
  FILE_TYPE_INVALID: 0,
  FILE_TYPE_FILE: 1,
  FILE_TYPE_FOLDER: 2
};

goog.object.extend(exports, proto.cs3.publicsharev0alpha);
